package com.sih.util

object Localization {
    private val translations = mapOf(
        "English" to mapOf(
            "app_name" to "NyayaDrishti",
            "home" to "Home",
            "inspect" to "Inspect",
            "history" to "History",
            "profile" to "Profile",
            "start_inspection" to "Start New Inspection",
            "good_morning" to "Good morning, Officer",
            "legal_metrology" to "Legal Metrology Inspection",
            "inspections" to "Inspections",
            "violations" to "Violations",
            "high_risk" to "High Risk",
            "recent_inspections" to "Recent Inspections",
            "select_method" to "Select Method",
            "scan_package" to "Scan Package",
            "upload_file" to "Upload Image/File",
            "online_listing" to "Online Listing",
            "compliance_result" to "Compliance Result",
            "compliance_score" to "Compliance Score",
            "view_evidence" to "View Evidence",
            "generate_report" to "Generate Report",
            "logout" to "Logout",
            "login" to "Login",
            "resume_inspection" to "Resume Inspection",
            "review_signoff" to "Review & Sign Off",
            "evidence_integrity" to "Evidence Integrity (SHA-256)",
            "quality_gate" to "Image Quality Gate",
            "unit_sale_price" to "Unit Sale Price (USP)",
            "package_geometry" to "Package Geometry Analysis",
            "officer_decision" to "Officer Decision",
            "confirm_violation" to "Confirm Violation",
            "mark_compliant" to "Mark Compliant",
            "unable_to_verify" to "Unable To Verify",
            "representative_ack" to "Representative Acknowledgement",
            "finalize_inspection" to "Finalize & Sign Off",
            "cloud_sync" to "Cloud Auto-Sync",
            "offline_mode" to "Autonomous Offline Mode",
            
            // Product Input & Establishment Strings
            "product_input_title" to "Product Details & Input",
            "commodity_compulsory" to "Commodity Name (Compulsory) *",
            "commodity_placeholder" to "e.g., Tomato Ketchup, Long Notebook, Mustard Oil...",
            "commodity_required_error" to "Commodity name is required before scanning",
            "commodity_hint" to "Prevents OCR from misinterpreting random packaging text",
            "quick_suggestions" to "Quick Suggestions:",
            "establishment_details_title" to "Establishment & Inspection Details",
            "establishment_label" to "Establishment / Shop Name",
            "establishment_placeholder" to "e.g., BigBasket Hub, Reliance Fresh",
            "location_label" to "Market / Location",
            "location_placeholder" to "e.g., Sector 18, Noida",
            "packages_label" to "Packages Count",
            "remarks_label" to "Officer Remarks / Reference (Optional)",
            "remarks_placeholder" to "e.g., Batch sample routine check",
            "scan_desc" to "Use camera to scan physical package in real-time.",
            "upload_desc" to "Analyze an existing photo or document.",
            "online_desc" to "Compare physical package MRP with online e-commerce price.",
            "statutory_config_title" to "Statutory Parameters & Checklist",
            "category_label" to "Packaging Commodity Category *",
            "unit_basis_label" to "Measurement Unit Basis *",
            "schedule_label" to "Statutory Enforcement Schedule *",
            "checklist_label" to "Active Inspection Checklist (Audit Scope) *",
            "checklist_auto_tuned" to "Rules automatically tailored to category & schedule. Tap to override.",
            "checklist_auto_badge" to "Auto-Tailored",
            "config_required_error" to "Please select category, unit basis, schedule and at least 1 checklist rule",
            
            // SignOff Strings
            "signoff_title" to "Officer Formal Sign-Off",
            "section_findings" to "Section 1: Finding Review",
            "section_ack" to "Section 2: Representative Acknowledgement",
            "section_finalization" to "Section 3: Finalization",
            "rep_name_label" to "Representative Name",
            "ack_disclaimer" to "Acknowledgement Status (Note: Acknowledgement does not imply agreement with findings)",
            "ack_receipt" to "I acknowledge receipt of this inspection report",
            "sign_finalize_button" to "Sign & Finalize",
            "finalize_confirm_title" to "Finalize Inspection",
            "finalize_confirm_text" to "Are you sure you want to finalize this inspection? This will generate a tamper-evident provenance hash."
        ),
        "Hindi" to mapOf(
            "app_name" to "न्यायदृष्टि",
            "home" to "होम",
            "inspect" to "निरीक्षण",
            "history" to "इतिहास",
            "profile" to "प्रोफ़ाइल",
            "start_inspection" to "नया निरीक्षण शुरू करें",
            "good_morning" to "सुप्रभात, अधिकारी",
            "legal_metrology" to "विधिक मापविज्ञान निरीक्षण",
            "inspections" to "निरीक्षण",
            "violations" to "उल्लंघन",
            "high_risk" to "उच्च जोखिम",
            "recent_inspections" to "हाल के निरीक्षण",
            "select_method" to "विधि चुनें",
            "scan_package" to "पैकेज स्कैन करें",
            "upload_file" to "छवि/फ़ाइल अपलोड करें",
            "online_listing" to "ऑनलाइन लिस्टिंग",
            "compliance_result" to "अनुपालन परिणाम",
            "compliance_score" to "अनुपालन स्कोर",
            "view_evidence" to "साक्ष्य देखें",
            "generate_report" to "रिपोर्ट तैयार करें",
            "logout" to "लॉग आउट",
            "login" to "लॉग इन",
            "resume_inspection" to "निरीक्षण पुनः आरंभ करें",
            "review_signoff" to "समीक्षा और हस्ताक्षर",
            "evidence_integrity" to "साक्ष्य अखंडता (SHA-256)",
            "quality_gate" to "छवि गुणवत्ता जांच",
            "unit_sale_price" to "इकाई बिक्री मूल्य (USP)",
            "package_geometry" to "पैकेज संरचना विश्लेषण",
            "officer_decision" to "अधिकारी का निर्णय",
            "confirm_violation" to "उल्लंघन की पुष्टि करें",
            "mark_compliant" to "अनुपालन के रूप में चिह्नित करें",
            "unable_to_verify" to "सत्यापित करने में असमर्थ",
            "representative_ack" to "प्रतिनिधि पावती",
            "finalize_inspection" to "अंतिम रूप दें और हस्ताक्षर करें",
            "cloud_sync" to "क्लाउड ऑटो-सिंक",
            "offline_mode" to "स्वायत्त ऑफ़लाइन मोड",
            
            "product_input_title" to "उत्पाद विवरण और इनपुट",
            "commodity_compulsory" to "वस्तु का नाम (अनिवार्य) *",
            "commodity_placeholder" to "उदा., टमाटर केचप, नोटबुक, सरसों का तेल...",
            "commodity_required_error" to "स्कैन करने से पहले वस्तु का नाम आवश्यक है",
            "commodity_hint" to "ओसीआर को पैकेजिंग पाठ का गलत अर्थ निकालने से रोकता है",
            "quick_suggestions" to "त्वरित सुझाव:",
            "establishment_details_title" to "प्रतिष्ठान और निरीक्षण विवरण",
            "establishment_label" to "प्रतिष्ठान / दुकान का नाम",
            "establishment_placeholder" to "उदा., बिगबास्केट हब, रिलायंस फ्रेश",
            "location_label" to "बाजार / स्थान",
            "location_placeholder" to "उदा., सेक्टर 18, नोएडा",
            "packages_label" to "पैकेजों की संख्या",
            "remarks_label" to "अधिकारी टिप्पणियाँ / संदर्भ (वैकल्पिक)",
            "remarks_placeholder" to "उदा., बैच नमूना नियमित जांच",
            "scan_desc" to "वास्तविक समय में पैकेज को स्कैन करने के लिए कैमरे का उपयोग करें।",
            "upload_desc" to "किसी मौजूदा फोटो या दस्तावेज़ का विश्लेषण करें।",
            "online_desc" to "ई-कॉमर्स कीमत के साथ भौतिक पैकेज एमआरपी की तुलना करें।",
            "statutory_config_title" to "सांविधिक पैरामीटर और चेकलिस्ट",
            "category_label" to "पैकेजिंग वस्तु श्रेणी *",
            "unit_basis_label" to "मापन इकाई आधार *",
            "schedule_label" to "सांविधिक प्रवर्तन अनुसूची *",
            "checklist_label" to "सक्रिय निरीक्षण चेकलिस्ट (ऑडिट दायरा) *",
            "checklist_auto_tuned" to "श्रेणी और अनुसूची के अनुसार नियम स्वतः समायोजित। बदलने के लिए टैप करें।",
            "checklist_auto_badge" to "स्वतः समायोजित",
            "config_required_error" to "कृपया श्रेणी, इकाई आधार, अनुसूची और कम से कम 1 चेकलिस्ट नियम चुनें",
            
            "signoff_title" to "अधिकारी का औपचारिक हस्ताक्षर",
            "section_findings" to "खंड 1: निष्कर्ष समीक्षा",
            "section_ack" to "खंड 2: प्रतिनिधि पावती",
            "section_finalization" to "खंड 3: समापन",
            "rep_name_label" to "प्रतिनिधि का नाम",
            "ack_disclaimer" to "पावती स्थिति (नोट: पावती का अर्थ निष्कर्षों से सहमति नहीं है)",
            "ack_receipt" to "मैं इस निरीक्षण रिपोर्ट की प्राप्ति स्वीकार करता हूं",
            "sign_finalize_button" to "हस्ताक्षर करें और अंतिम रूप दें",
            "finalize_confirm_title" to "निरीक्षण को अंतिम रूप दें",
            "finalize_confirm_text" to "क्या आप निश्चित रूप से इस निरीक्षण को अंतिम रूप देना चाहते हैं? यह एक साक्ष्य हैश उत्पन्न करेगा।"
        ),
        "Tamil" to mapOf(
            "app_name" to "நியாயதிருஷ்டி",
            "home" to "முகப்பு",
            "inspect" to "ஆய்வு",
            "history" to "வரலாறு",
            "profile" to "சுயவிவரம்",
            "start_inspection" to "புதிய ஆய்வைத் தொடங்கு",
            "good_morning" to "காலை வணக்கம், அதிகாரி",
            "legal_metrology" to "சட்ட அளவியல் ஆய்வு",
            "inspections" to "ஆய்வுகள்",
            "violations" to "மீறல்கள்",
            "high_risk" to "அதிக ஆபத்து",
            "recent_inspections" to "சமீபத்திய ஆய்வுகள்",
            "select_method" to "முறையைத் தேர்ந்தெடுக்கவும்",
            "scan_package" to "தொகுப்பை ஸ்கேன் செய்",
            "upload_file" to "படம்/கோப்பைப் பதிவேற்று",
            "online_listing" to "ஆன்லைன் பட்டியல்",
            "compliance_result" to "இணக்க முடிவு",
            "compliance_score" to "இணக்க மதிப்பெண்",
            "view_evidence" to "ஆதாரத்தைப் பார்",
            "generate_report" to "அறிக்கையை உருவாக்கு",
            "logout" to "வெளியேறு",
            "login" to "உள்நுழை",
            "resume_inspection" to "ஆய்வை மீண்டும் தொடங்கு",
            "review_signoff" to "மதிப்பாய்வு மற்றும் கையொப்பம்",
            "evidence_integrity" to "ஆதாரத்தின் நம்பகத்தன்மை (SHA-256)",
            "quality_gate" to "படத்தின் தர சோதனை",
            "unit_sale_price" to "அலகு விற்பனை விலை (USP)",
            "package_geometry" to "தொகுப்பு வடிவியல் பகுப்பாய்வு",
            "officer_decision" to "அதிகாரியின் முடிவு",
            "confirm_violation" to "மீறலை உறுதிப்படுத்து",
            "mark_compliant" to "இணக்கமாகக் குறிக்கவும்",
            "unable_to_verify" to "சரிபார்க்க முடியவில்லை",
            "representative_ack" to "பிரதிநிதி ஒப்புதல்",
            "finalize_inspection" to "இறுதி செய்து கையொப்பமிடு",
            "cloud_sync" to "மேகக்கணி தானியங்கி ஒத்திசைவு",
            "offline_mode" to "ஆஃப்லைன் பயன்முறை",
            
            "product_input_title" to "பொருள் விவரங்கள் & உள்ளீடு",
            "commodity_compulsory" to "பொருளின் பெயர் (கட்டாயம்) *",
            "commodity_placeholder" to "எ.கா., தக்காளி சாஸ், நோட்டுப்புத்தகம், கடுகு எண்ணெய்...",
            "commodity_required_error" to "ஸ்கேன் செய்வதற்கு முன் பொருளின் பெயர் தேவை",
            "commodity_hint" to "பேக்கேஜிங் உரையை தவறாகப் புரிந்துகொள்வதைத் தடுக்கிறது",
            "quick_suggestions" to "வேகமான பரிந்துரைகள்:",
            "establishment_details_title" to "நிறுவனம் & ஆய்வு விவரங்கள்",
            "establishment_label" to "நிறுவனம் / கடை பெயர்",
            "establishment_placeholder" to "எ.கா., பிக்பாஸ்கெட் ஹப், ரிலையன்ஸ் ப்ரெஷ்",
            "location_label" to "சந்தை / இடம்",
            "location_placeholder" to "எ.கா., செக்டர் 18, நொய்டா",
            "packages_label" to "தொகுப்புகளின் எண்ணிக்கை",
            "remarks_label" to "அதிகாரி குறிப்புகள் (விருப்பத்தேர்வு)",
            "remarks_placeholder" to "எ.கா., மாதிரி சோதனைக் குழு",
            "scan_desc" to "தொகுப்பை ஸ்கேன் செய்ய கேமராவைப் பயன்படுத்தவும்.",
            "upload_desc" to "ஏற்கனவே உள்ள புகைப்படம் அல்லது ஆவணத்தை பகுப்பாய்வு செய்யவும்.",
            "online_desc" to "ஈ-காமர்ஸ் விலையுடன் தொகுப்பு MRP ஐ ஒப்பிடவும்.",
            
            "signoff_title" to "அதிகாரப்பூர்வ கையொப்பம்",
            "section_findings" to "பிரிவு 1: கண்டுபிடிப்பு மதிப்பாய்வு",
            "section_ack" to "பிரிவு 2: பிரதிநிதி ஒப்புதல்",
            "section_finalization" to "பிரிவு 3: முடிவுறுத்தல்",
            "rep_name_label" to "பிரதிநிதியின் பெயர்",
            "ack_disclaimer" to "ஒப்புதல் நிலை (குறிப்பு: ஒப்புதல் என்பது கண்டுபிடிப்புகளுடன் உடன்பாட்டைக் குறிக்காது)",
            "ack_receipt" to "இந்த ஆய்வு அறிக்கையைப் பெற்றதை நான் ஒப்புக்கொள்கிறேன்",
            "sign_finalize_button" to "கையெழுத்திட்டு முடிவாக்கு",
            "finalize_confirm_title" to "ஆய்வை முடிவாக்கு",
            "finalize_confirm_text" to "இந்த ஆய்வை இறுதி செய்ய விரும்புகிறீர்களா? இது சான்றளிப்பு ஹேஷை உருவாக்கும்."
        ),
        "Telugu" to mapOf(
            "app_name" to "న్యాయదృష్టి",
            "home" to "హోమ్",
            "inspect" to "తనిఖీ",
            "history" to "చరిత్ర",
            "profile" to "ప్రొఫైల్",
            "start_inspection" to "కొత్త తనిఖీని ప్రారంభించండి",
            "good_morning" to "శుభోదయం, అధికారి",
            "legal_metrology" to "లీగల్ మెట్రాలజీ తనిఖీ",
            "inspections" to "తనిఖీలు",
            "violations" to "ఉల్లంఘనలు",
            "high_risk" to "అధిక ప్రమాదం",
            "recent_inspections" to "ఇటీవలి తనిఖీలు",
            "select_method" to "పద్ధతిని ఎంచుకోండి",
            "scan_package" to "ప్యాకేజీని స్కాన్ చేయండి",
            "upload_file" to "చిత్రం/ఫైల్‌ను అప్‌లోడ్ చేయండి",
            "online_listing" to "ఆన్‌లైన్ లిస్టింగ్",
            "compliance_result" to "అనుకూలత ఫలితం",
            "compliance_score" to "అనుకూలత స్కోరు",
            "view_evidence" to "సాక్ష్యాలను చూడండి",
            "generate_report" to "నివేదికను రూపొందించండి",
            "logout" to "లాగ్ అవుట్",
            "login" to "లాగిన్",
            "resume_inspection" to "తనిఖీని పునఃప్రారంభించండి",
            "review_signoff" to "సమీక్ష మరియు సంతకం",
            "evidence_integrity" to "సాక్ష్య సమగ్రత (SHA-256)",
            "quality_gate" to "చిత్ర నాణ్యత తనిఖీ",
            "unit_sale_price" to "యూనిట్ విక్రయ ధర (USP)",
            "package_geometry" to "ప్యాకేజీ జ్యామితి విశ్లేషణ",
            "officer_decision" to "అధికారి నిర్ణయం",
            "confirm_violation" to "ఉల్లంఘనను ధృవీకరించండి",
            "mark_compliant" to "అనుకూలమైనదిగా గుర్తించండి",
            "unable_to_verify" to "తనిఖీ చేయడం సాధ్యపడలేదు",
            "representative_ack" to "ప్రతినిధి రసీదు",
            "finalize_inspection" to "పూర్తి చేసి సంతకం చేయండి",
            "cloud_sync" to "క్లౌడ్ ఆటో-సింక్",
            "offline_mode" to "ఆఫ్‌లైన్ మోడ్",
            
            "product_input_title" to "ఉత్పత్తి వివరాలు & ఇన్‌పుట్",
            "commodity_compulsory" to "వస్తువు పేరు (తప్పనిసరి) *",
            "commodity_placeholder" to "ఉదా., టమాటో కేచప్, నోట్‌బుక్, ఆయిల్...",
            "commodity_required_error" to "స్కాన్ చేయడానికి ముందు వస్తువు పేరు అవసరం",
            "commodity_hint" to "తప్పుగా అర్ధం చేసుకోవడాన్ని నివారిస్తుంది",
            "quick_suggestions" to "త్వరిత సూచనలు:",
            "establishment_details_title" to "సంస్థ & తనిఖీ వివరాలు",
            "establishment_label" to "సంస్థ / దుకాణం పేరు",
            "establishment_placeholder" to "ఉదా., బిగ్‌బాస్కెట్ హబ్, రిలయన్స్ ఫ్రెష్",
            "location_label" to "మార్కెట్ / ప్రాంతం",
            "location_placeholder" to "ఉదా., సెక్టార్ 18, నోయిడా",
            "packages_label" to "ప్యాకేజీల సంఖ్య",
            "remarks_label" to "అధికారి వ్యాఖ్యలు (ఐచ్ఛికం)",
            "remarks_placeholder" to "ఉదా., సాధారణ నమూనా తనిఖీ",
            "scan_desc" to "ప్యాకేజీని స్కాన్ చేయడానికి కెమెరాను ఉపయోగించండి.",
            "upload_desc" to "ఇప్పటికే ఉన్న ఫోటోను విశ్లేషించండి.",
            "online_desc" to "ఇ-కామర్స్ ధరతో MRP ని పోల్చండి.",
            
            "signoff_title" to "అధికారి అధికారిక సంతకం",
            "section_findings" to "విభాగం 1: ఫలితాల సమీక్ష",
            "section_ack" to "విభాగం 2: ప్రతినిధి రసీదు",
            "section_finalization" to "విభాగం 3: ముగింపు",
            "rep_name_label" to "ప్రతినిధి పేరు",
            "ack_disclaimer" to "రసీదు స్థితి (గమనిక: రసీదు అంటే అంగీకారం అని అర్థం కాదు)",
            "ack_receipt" to "నేను ఈ తనిఖీ నివేదిక రసీదును అంగీకరిస్తున్నాను",
            "sign_finalize_button" to "సంతకం చేసి పూర్తి చేయండి",
            "finalize_confirm_title" to "తనిఖీని పూర్తి చేయండి",
            "finalize_confirm_text" to "మీరు ఖచ్చితంగా ఈ తనిఖీని పూర్తి చేయాలనుకుంటున్నారా?"
        ),
        "Kannada" to mapOf(
            "app_name" to "ನ್ಯಾಯದೃಷ್ಟಿ",
            "home" to "ಹೋಮ್",
            "inspect" to "ತಪಾಸಣೆ",
            "history" to "ಇತಿಹಾಸ",
            "profile" to "ಪ್ರೊಫೈಲ್",
            "start_inspection" to "ಹೊಸ ತಪಾಸಣೆ ಪ್ರಾರಂಭಿಸಿ",
            "good_morning" to "ಶುಭೋದಯ, ಅಧಿಕಾರಿ",
            "legal_metrology" to "ಕಾನೂನು ಮಾಪನಶಾಸ್ತ್ರ ತಪಾಸಣೆ",
            "inspections" to "ತಪಾಸಣೆಗಳು",
            "violations" to "ಉಲ್ಲಂಘನೆಗಳು",
            "high_risk" to "ಹೆಚ್ಚಿನ ಅಪಾಯ",
            "recent_inspections" to "ಇತ್ತೀಚಿನ ತಪಾಸಣೆಗಳು",
            "select_method" to "ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            "scan_package" to "ಪ್ಯಾಕೇಜ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
            "upload_file" to "ಚಿತ್ರ/ಫೈಲ್ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
            "online_listing" to "ಆನ್‌ಲೈನ್ ಲಿಸ್ಟಿಂಗ್",
            "compliance_result" to "ಅನುಸರಣೆ ಫಲಿತಾಂಶ",
            "compliance_score" to "ಅನುಸರಣೆ ಸ್ಕೋರ್",
            "view_evidence" to "ಪುರಾವೆ ನೋಡಿ",
            "generate_report" to "ವರದಿ ತಯಾರಿಸಿ",
            "logout" to "ಲಾಗ್ ಔಟ್",
            "login" to "ಲಾಗ್ ಇನ್",
            "resume_inspection" to "ತಪಾಸಣೆ ಪುನರಾರಂಭಿಸಿ",
            "review_signoff" to "ಪರಿಶೀಲನೆ ಮತ್ತು ಸಹಿ",
            "evidence_integrity" to "ಸಾಕ್ಷ್ಯದ ಸಮಗ್ರತೆ (SHA-256)",
            "quality_gate" to "ಚಿತ್ರದ ಗುಣಮಟ್ಟ ಪರೀಕ್ಷೆ",
            "unit_sale_price" to "ಘಟಕ ಮಾರಾಟ ಬೆಲೆ (USP)",
            "package_geometry" to "ಪ್ಯಾಕೇಜ್ ಜ್ಯಾಮಿತಿ ವಿಶ್ಲೇಷಣೆ",
            "officer_decision" to "ಅಧಿಕಾರಿಯ ನಿರ್ಧಾರ",
            "confirm_violation" to "ಉಲ್ಲಂಘನೆಯನ್ನು ಖಚಿತಪಡಿಸಿ",
            "mark_compliant" to "ಅನುಸರಣೆ ಎಂದು ಗುರುತಿಸಿ",
            "unable_to_verify" to "ಪರಿಶೀಲಿಸಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ",
            "representative_ack" to "ಪ್ರತಿನಿಧಿ ಸ್ವೀಕೃತಿ",
            "finalize_inspection" to "ಅಂತಿಮಗೊಳಿಸಿ ಸಹಿ ಮಾಡಿ",
            "cloud_sync" to "ಕ್ಲೌಡ್ ಆಟೋ-ಸಿಂಕ್",
            "offline_mode" to "ಆಫ್‌ಲೈನ್ ಮೋಡ್",
            
            "product_input_title" to "ಉತ್ಪನ್ನ ವಿವರಗಳು ಮತ್ತು ಇನ್‌ಪುಟ್",
            "commodity_compulsory" to "ವಸ್ತುವಿನ ಹೆಸರು (ಕಡ್ಡಾಯ) *",
            "commodity_placeholder" to "ಉದಾ., ಟೊಮೆಟೊ ಕೆಚಪ್, ನೋಟ್‌ಬುಕ್, ಎಣ್ಣೆ...",
            "commodity_required_error" to "ಸ್ಕ್ಯಾನ್ ಮಾಡುವ ಮೊದಲು ವಸ್ತುವಿನ ಹೆಸರು ಅಗತ್ಯವಿದೆ",
            "commodity_hint" to "ಪಠ್ಯವನ್ನು ತಪ್ಪಾಗಿ ಅರ್ಥೈಸಿಕೊಳ್ಳುವುದನ್ನು ತಡೆಯುತ್ತದೆ",
            "quick_suggestions" to "ತ್ವರಿತ ಸಲಹೆಗಳು:",
            "establishment_details_title" to "ಸಂಸ್ಥೆ ಮತ್ತು ತಪಾಸಣೆ ವಿವರಗಳು",
            "establishment_label" to "ಸಂಸ್ಥೆ / ಅಂಗಡಿಯ ಹೆಸರು",
            "establishment_placeholder" to "ಉದಾ., ಬಿಗ್‌ಬಾಸ್ಕೆಟ್ ಹಬ್, ರಿಲಯನ್ಸ್ ಫ್ರೆಶ್",
            "location_label" to "ಮಾರುಕಟ್ಟೆ / ಸ್ಥಳ",
            "location_placeholder" to "ಉದಾ., ಸೆಕ್ಟರ್ 18, ನೋಯ್ಡಾ",
            "packages_label" to "ಪ್ಯಾಕೇಜ್‌ಗಳ ಸಂಖ್ಯೆ",
            "remarks_label" to "ಅಧಿಕಾರಿ ಟಿಪ್ಪಣಿಗಳು (ಐಚ್ಛಿಕ)",
            "remarks_placeholder" to "ಉದಾ., ಮಾದರಿ ತಪಾಸಣೆ",
            "scan_desc" to "ಪ್ಯಾಕೇಜ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ಕ್ಯಾಮೆರಾ ಬಳಸಿ.",
            "upload_desc" to "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಫೋಟೋವನ್ನು ವಿಶ್ಲೇಷಿಸಿ.",
            "online_desc" to "ಇ-ಕಾಮರ್ಸ್ ಬೆಲೆಯೊಂದಿಗೆ MRP ಹೋಲಿಸಿ.",
            
            "signoff_title" to "ಅಧಿಕಾರಿಯ ಅಧಿಕೃತ ಸಹಿ",
            "section_findings" to "ವಿಭಾಗ 1: ಸಂಶೋಧನೆಗಳ ಪರಿಶೀಲನೆ",
            "section_ack" to "ವಿಭಾಗ 2: ಪ್ರತಿನಿಧಿ ಸ್ವೀಕೃತಿ",
            "section_finalization" to "ವಿಭಾಗ 3: ಮುಕ್ತಾಯ",
            "rep_name_label" to "ಪ್ರತಿನಿಧಿಯ ಹೆಸರು",
            "ack_disclaimer" to "ಸ್ವೀಕೃತಿ ಸ್ಥಿತಿ (ಗಮನಿಸಿ: ಸ್ವೀಕೃತಿಯು ಒಪ್ಪಂದವನ್ನು ಸೂಚಿಸುವುದಿಲ್ಲ)",
            "ack_receipt" to "ನಾನು ಈ ತಪಾಸಣೆ ವರದಿಯ ಸ್ವೀಕೃತಿಯನ್ನು ಒಪ್ಪಿಕೊಳ್ಳುತ್ತೇನೆ",
            "sign_finalize_button" to "ಸಹಿ ಮಾಡಿ ಅಂತಿಮಗೊಳಿಸಿ",
            "finalize_confirm_title" to "ತಪಾಸಣೆಯನ್ನು ಅಂತಿಮಗೊಳಿಸಿ",
            "finalize_confirm_text" to "ನೀವು ಖಂಡಿತವಾಗಿಯೂ ಈ ತಪಾಸಣೆಯನ್ನು ಅಂತಿಮಗೊಳಿಸಲು ಬಯಸುತ್ತೀರಾ?"
        ),
        "Malayalam" to mapOf(
            "app_name" to "ന്യായാദൃഷ്ടി",
            "home" to "ഹോം",
            "inspect" to "പരിശോധന",
            "history" to "ചരിത്രം",
            "profile" to "പ്രൊഫൈൽ",
            "start_inspection" to "പുതിയ പരിശോധന തുടങ്ങുക",
            "good_morning" to "സുപ്രഭാതം, ഉദ്യോഗസ്ഥൻ",
            "legal_metrology" to "ലീഗൽ മെട്രോളജി പരിശോധന",
            "inspections" to "പരിശോധനകൾ",
            "violations" to "ലംഘനങ്ങൾ",
            "high_risk" to "ഉയർന്ന അപകടസാധ്യത",
            "recent_inspections" to "സമീപകാല പരിശോധനകൾ",
            "select_method" to "രീതി തിരഞ്ഞെടുക്കുക",
            "scan_package" to "പാക്കേജ് സ്കാൻ ചെയ്യുക",
            "upload_file" to "ചിത്രം/ഫയൽ അപ്‌ലോഡ് ചെയ്യുക",
            "online_listing" to "ഓൺലൈൻ ലിസ്റ്റിംഗ്",
            "compliance_result" to "പാലിക്കൽ ഫലം",
            "compliance_score" to "പാലിക്കൽ സ്കോർ",
            "view_evidence" to "തെളിവ് കാണുക",
            "generate_report" to "റിപ്പോർട്ട് തയ്യാറാക്കുക",
            "logout" to "ലോഗൗട്ട്",
            "login" to "ലോഗിൻ",
            "resume_inspection" to "പരിശോധന പുനരാരംഭിക്കുക",
            "review_signoff" to "വിലയിരുത്തലും ഒപ്പുവയ്ക്കലും",
            "evidence_integrity" to "തെളിവ് സുതാര്യത (SHA-256)",
            "quality_gate" to "ചിത്ര ഗുണനിലവാര പരിശോധന",
            "unit_sale_price" to "യൂണിറ്റ് വിൽപന വില (USP)",
            "package_geometry" to "പാക്കേജ് ഘടന വിശകലനം",
            "officer_decision" to "ഉദ്യോഗസ്ഥന്റെ തീരുമാനം",
            "confirm_violation" to "ലംഘനം സ്ഥിരീകരിക്കുക",
            "mark_compliant" to "പാലിക്കപ്പെട്ടതായി അടയാളപ്പെടുത്തുക",
            "unable_to_verify" to "സ്ഥിരീകരിക്കാൻ കഴിഞ്ഞില്ല",
            "representative_ack" to "പ്രതിനിധി രസീത്",
            "finalize_inspection" to "അന്തിമമാക്കി ഒപ്പുവയ്ക്കുക",
            "cloud_sync" to "ക്ലൗഡ് ഓട്ടോ-സിങ്ക്",
            "offline_mode" to "ഓഫ്‌ലൈൻ മോഡ്",
            
            "product_input_title" to "ഉൽപ്പന്ന വിവരങ്ങളും ഇൻപുട്ടും",
            "commodity_compulsory" to "ഉൽപ്പന്നത്തിന്റെ പേര് (നിർബന്ധം) *",
            "commodity_placeholder" to "ഉദാ., തക്കാളി കെച്ചപ്പ്, നോട്ട്ബുക്ക്, എണ്ണ...",
            "commodity_required_error" to "സ്കാൻ ചെയ്യുന്നതിന് മുൻപ് ഉൽപ്പന്നത്തിന്റെ പേര് ആവശ്യമാണ്",
            "commodity_hint" to "തെറ്റായി മനസ്സിലാക്കുന്നത് തടയുന്നു",
            "quick_suggestions" to "വേഗത്തിലുള്ള നിർദ്ദേശങ്ങൾ:",
            "establishment_details_title" to "സ്ഥാപനത്തിന്റെയും പരിശോധനയുടെയും വിവരങ്ങൾ",
            "establishment_label" to "സ്ഥാപനം / കടയുടെ പേര്",
            "establishment_placeholder" to "ഉദാ., ബിഗ്ബാസ്ക്കറ്റ് ഹബ്ബ്, റിലയൻസ് ഫ്രഷ്",
            "location_label" to "മാർക്കറ്റ് / സ്ഥലം",
            "location_placeholder" to "ഉദാ., സെക്ടർ 18, നോയിഡ",
            "packages_label" to "പാക്കറ്റുകളുടെ എണ്ണം",
            "remarks_label" to "ഉദ്യോഗസ്ഥന്റെ അഭിപ്രായങ്ങൾ (ഓപ്ഷണൽ)",
            "remarks_placeholder" to "ഉദാ., മാതൃകാ പരിശോധന",
            "scan_desc" to "പാക്കേജ് സ്കാൻ ചെയ്യാൻ ക്യാമറ ഉപയോഗിക്കുക.",
            "upload_desc" to "നിലവിലുള്ള ചിത്രം വിശകലനം ചെയ്യുക.",
            "online_desc" to "ഇ-കോമേഴ്സ് വിലയുമായി MRP താരതമ്യം ചെയ്യുക.",
            
            "signoff_title" to "ഉദ്യോഗസ്ഥന്റെ ഔദ്യോഗിക ഒപ്പ്",
            "section_findings" to "വിഭാഗം 1: കണ്ടെത്തലുകളുടെ അവലോകനം",
            "section_ack" to "വിഭാഗം 2: പ്രതിനിധി രസീത്",
            "section_finalization" to "വിഭാഗം 3: അന്തിമമാക്കൽ",
            "rep_name_label" to "പ്രതിനിധിയുടെ പേര്",
            "ack_disclaimer" to "രസീത് നില (ശ്രദ്ധിക്കുക: രസീത് എന്നാൽ യോജിപ്പല്ല)",
            "ack_receipt" to "ഈ പരിശോധനാ റിപ്പോർട്ടിന്റെ രസീത് ഞാൻ കൈപ്പറ്റുന്നു",
            "sign_finalize_button" to "ഒപ്പുവെച്ച് അന്തിമമാക്കുക",
            "finalize_confirm_title" to "പരിശോധന അന്തിമമാക്കുക",
            "finalize_confirm_text" to "തീർച്ചയായും ഈ പരിശോധന അന്തിമമാക്കണമെന്നുണ്ടോ?"
        )
    )

    fun getString(key: String, language: String): String {
        return translations[language]?.get(key) ?: translations["English"]?.get(key) ?: key
    }

    fun getDualString(key: String, language: String): String {
        val regional = getString(key, language)
        val english = translations["English"]?.get(key) ?: return regional
        
        return if (language == "English") {
            regional
        } else {
            "$regional / $english"
        }
    }
}
